Feature evaulate and replace variables in config
TaskarCenterAtUW/TDEI-infra-as-code pull request #111
Opened 2023-07-17 07:12 UTC by santaduda

- Replaced app services config with keyvault values
- Updated PostgreSQL instance name in config
- Stored PostgreSQL credentials in Keyvault

2023-07-17 07:46 UTC, susrisha requested changes
One minor change from commandline to mgmt based calls
One major change to move to chevron. (can be taken up as another task )

2023-07-17 07:46 UTC, susrisha commented on infra/keyvault/keyvault.py
> +        command = 'az keyvault show --name ' + cls.key_vault_name
can this not be made using azure python SDK?

2023-07-17 07:46 UTC, susrisha commented on infra/keyvault/keyvault.py
> +                print('Failed to create keyvault')
could have tried with https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-mgmt-keyvault/generated_samples/create_vault.py example code instead of relying on the commandline

2023-07-17 07:46 UTC, susrisha commented on infra/keyvault/keyvault.py
> +    def substitue_expression(cls, microservices_config):
can we please use any templating engine for this? its a far better way than doing regex replace.
Repo link https://github.com/noahmorrison/chevron

2023-07-17 07:46 UTC, susrisha commented on infra/keyvault/keyvault.py
> +class KeyVault(object):
Any specific reason for making this as singleton?

2023-07-19 08:25 UTC, santaduda commented on infra/keyvault/keyvault.py
> +    def substitue_expression(cls, microservices_config):
Templating engine does not provide us with info on what variables were missing during replacement.
Also we have to fetch all Azure variables and provide to the replacement which may not be needed.

2023-07-19 08:30 UTC, santaduda commented on infra/keyvault/keyvault.py
> +class KeyVault(object):
We can use it throughout all modules without having to pass resource group, credentials and environment parameters all the time. Also it would always have all the keyvault attributes in it and we can use getter and setter methods to get and set the key vaules.

2023-07-19 10:15 UTC, santaduda commented on infra/keyvault/keyvault.py
> +        command = 'az keyvault show --name ' + cls.key_vault_name
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-mgmt-keyvault/generated_samples/create_vault.py

Requires many parameters (like properties , accessPolicies, etc) which is mandatory for creating the KeyVault using KeyVaultManagementClient. So we will create a task for refactoring it using KeyVaultManagementClient in the future.

2023-07-19 10:16 UTC, santaduda commented on infra/keyvault/keyvault.py
> +                print('Failed to create keyvault')
Same comment as above.

2023-07-19 10:40 UTC, rdevalap approved these changes

2023-07-19 11:03 UTC, susrisha approved these changes

2023-07-19 11:41 UTC, merged