Update app service params after provisioning
TaskarCenterAtUW/TDEI-infra-as-code pull request #117
Opened 2023-07-24 07:55 UTC by santaduda

After app services are provisioned the app service parameters and KeyVault values are set.

2023-07-24 10:41 UTC, rdevalap requested changes
Hi @santaduda , As discussed,
1. Can you add the parameters for all app services?
2. Can you comment the line `KeyVault.substitue_expression(microservices_config)` in `diagnostic-settings.py`

2023-07-24 10:41 UTC, rdevalap commented on create-env.py
> +            credential=DefaultAzureCredential(exclude_shared_token_cache_credential=True),
I do not have this issue. Can you rollback this? Keep it DefaultAzureCredential?

2023-07-24 10:48 UTC, rdevalap commented on create-env.py
> +            credential=DefaultAzureCredential(exclude_shared_token_cache_credential=True),
Also, test it from the github workflow?

2023-07-24 11:02 UTC, rdevalap commented on create-env.py
> +            credential=DefaultAzureCredential(exclude_shared_token_cache_credential=True),
Also, remove the "After" in Keyvault.substitute?

2023-07-24 11:24 UTC, santaduda commented
1. Added all microservices and application parameters
2. Removed exclude_shared_token_cache_credential=True in DefaultAzureCredential()
3. Commented line : KeyVault.substitue_expression(microservices_config) in diagnostic-settings.py

2023-07-25 07:05 UTC, rdevalap approved these changes
Tested the code. Works well. 
Provisions app services, configures health check, diagnostic settings enabled

2023-07-25 07:14 UTC, merged